---
engine: knitr
---

### Contributing Overview

A comprehensive and accessible coding bilingualism website like this one is a huge undertaking and I'd welcome collaborators who share my vision for the value of a resource like this. I'm a competent [{{< fa brands r-project >}} R]{.r} coder but that definitely does not mean I am 100% correct all the time nor that I always write explanations in the clearest way possible. On the [{{< fa brands python >}} Python]{.py} front, my first real foray into that coding language is taking tutorials and starting this website (in 2023).

So, if you'd like to collaborate with me on this I have drafted the following guidelines. I'm happy to discuss/modify these with prospective collaborators so please don't let them dissuade you from reaching out!

### Note on "Artificial Intelligence"

Please **_do not_** use generative AI for _any_ facet of your contribution to this work. AI is a random number generator built on plagiarism with an absurd error rate so from ethical and practical perspectives I'm not interested in including content produced in that way in this effort. I am absolutely interested in the ways in which _your_ curiosity and insight can benefit this product though, so please do contribute if you have an idea for improving this resource.

Relatedly, I will not be developing any content for this website on how to effectively use AI in either an [{{< fa brands r-project >}} R]{.r} or [{{< fa brands python >}} Python]{.py} context. Proponents of AI often argue that AI is extremely user-friendly so surely those interested in using AI for coding in these languages should be able to teach themselves elsewhere.

### Bug / Issue Reporting

If you see something wrong--either in a code chunk or in the plain text--I'd really appreciate it if you flagged it for my attention. You can do this by opening a {{< fa brands github >}} [GitHub Issue](https://github.com/njlyon0/collab_bilingualism/issues) on this project's repository. Please include the link to the page with the problem and as much detail as possible so I can easily find the problem area and make any needed repairs.

If you identify a bug in this manner I'll add your name (and the link to the professional website of your choosing) to the list below!

#### Bug Finders {{< fa bugs >}}

- Timothy Divoll -- {{< fa brands github >}} [GitHub profile](https://github.com/tdivoll)

### Co-Development

If you'd like to actively collaborate with me on developing and refining this website that would be awesome! Please either reach out to me directly ([see my website](https://njlyon0.github.io/) for my contact info) or open a {{< fa brands github >}} [GitHub Issue](https://github.com/njlyon0/collab_bilingualism/issues) to get that conversation started.

I'm envisioning that each new collaborator would (1) [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the website's GitHub repository, (2) make any edits that they had in mind, and (3) then [submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) to get those changes integrated into the primary website. I feel this minimizes the risk that changes have unintentional consequences for the website rendering as whole. I'm absolutely open to a [branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches)-based alternative if that makes more sense and I anticipate refining the logistical elements of contributing once the development team grows somewhat.

### Contribution Credit

If you are interested/willing to join me in refining this website, I believe that is absolutely worthy of formal credit. You'll notice that the top right of the navbar has a "Creators" dropdown menu. If you contribute substantively (e.g., demonstrating new tools, adding a new page, etc.) we can add your name to the dropdown and link it to the professional website of your choosing.

If you have other modes of properly acknowledging your contribution(s) in mind I am absolutely open to discussing those ideas!
