---
title: "Spatial Fundamentals"
engine: knitr
---

## Library Loading

Begin by loading any needed libraries.

:::panel-tabset
## [{{< fa brands r-project >}}]{.r} R

Load `sf` and `terra`.

```{r r-libs, warning = F, message = F}
library(sf)
library(terra)
```

## [{{< fa brands python >}}]{.py} Python

Load the `geopandas` and `rasterio` libraries.

```{python py-libs}
# Load needed libraries
import geopandas as gpd
import rasterio
```
:::

## Spatial Data Types

Under Construction, check back soon!



## Coordinate Reference Systems (CRS)

### Checking CRS


### Transforming CRS





## Additional Resources

Spatial operations have gotten _a ton_ of attention in both [{{< fa brands python >}} Python]{.py} and [{{< fa brands r-project >}} R]{.r}! This website is mostly focused on translating between the two languages though so much of this nuance is not covered here. For those interested in a deeper dive in spatial computing, consider the following.

- [{{< fa brands r-project >}} R]{.r} -- [Rachel King](https://github.com/king0708) created a really nice ["Spatial Data Visualization"](https://github.com/king0708/spatial-data-viz) workshop
- [{{< fa brands python >}} Python]{.py} -- The Arctic Data Center made a "Scalable and Computationally Reproducible Approaches to Arctic Resources" course that includes a ["Spatial and Image Data Using GeoPandas"](https://learning.nceas.ucsb.edu/2023-03-arctic/sections/geopandas.html#calculate-total-distance-per-fishing-area) chapter
